name = "aprova-plataforma"
main = "server/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[assets]
directory = "./dist"

[vars]
APP_NAME = "APROVA"
APP_ENV = "production"
