name = "aprova-plataforma"
main = "server/worker.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run build"

[assets]
directory = "./dist"
not_found_handling = "single-page-application"

[vars]
APP_NAME = "APROVA"
APP_ENV = "production"
